[package]
name = "find-first-bt-radio-3"
version = "0.1.0"
edition = "2024"

[dependencies.windows]
version = "0.60.0"
features = [
    "Win32",
    "Win32_Devices_Bluetooth",
    "Win32_Foundation",
]