[package]
name = "find-all-bt-radio-4"
version = "0.1.0"
edition = "2024"

[dependencies.windows]
version = "0.60.0"
features = [
    "Win32",
    "Win32_Foundation",
    "Win32_Devices_Bluetooth",
]
